export const REGIONALS_DATA: Record<string, string[]> = {
  "Regional 01": ["Sede"],
  "Regional 02": [
    "Estrela do Sul",
    "Cidade Vera Cruz 2",
    "Conj. Santa Fé",
    "Jardim Luz",
    "Vila Rosa",
  ],
  "Regional 03": [
    "Veiga Jardim",
    "Cidade Vera Cruz 3",
    "Res. Alva Luz",
    "Terra Prometida",
  ],
  "Regional 04": [
    "Pontal Sul",
    "Pontal Sul 2",
    "Village Garavelo",
    "Jardim Girassóis",
  ],
  "Regional 05": [
    "Oriente Ville",
    "Cond. Esmeralda 1",
    "Res. Real Conquista",
    "Jardim Ipanema",
    "Res. Itaipú",
  ],
  "Regional 06": [
    "Morada",
    "São Carlos",
    "Brisas da Mata",
    "Estrela D'Alva",
    "Lago Azul",
    "Vista Bela",
  ],
  "Regional 07": [
    "Porto Dourado",
    "Aragoiania",
    "Crominia",
    "Jardim dos Ipês",
    "Madre Germana 1",
    "Quinta da Boa Vista",
  ],
  "Regional 08": [
    "Hidrolandia",
    "Jardim Miramar",
    "Parque Flamboyant",
    "Parque Paraíso",
    "Bairro Goiá",
  ],
  "Regional 09": ["Beatriz Nascimento", "Jardim Imperial"],
  "Regional 10": ["Nerópolis", "Res. Fratelli", "Santo Antonio de Goiás"],
  "Regional 11": ["Colina Azul", "Jardim Ipiranga", "Virginia Park"],
  "Regional 12": [
    "Triunfo 2",
    "Nova Goianira",
    "Paineiras",
    "Res. Araguaia",
    "Setor Sul",
    "Triunfo 1",
    "Triunfo 3",
  ],
  "Regional 13": ["Buriti de Goiás", "Jaupaci", "Jussara", "Parauna"],
  "Regional 14": [
    "Jardim do Cerrado 4",
    "Alto do Cerrado",
    "Lírios do Campo",
    "Monte Pascoal 1",
    "Monte Pascoal 2",
    "Res. Portinari",
  ],
  "Regional 15": [
    "Res. Pedro Miranda",
    "Flor do Ipê",
    "Res. Primavera",
    "Setor Alvorada",
    "Vila Galvão",
  ],
  "Regional 16": [
    "Orlando de Morais",
    "Montes Claros",
    "Bela Goiania",
    "Res. Morumbi",
    "Vale dos Sonhos",
  ],
  "Regional 17": [
    "Abadia Central",
    "Goiania Sul",
    "Porto Seguro - Abadia",
    "Res. Dori",
    "Res. Primavera",
  ],
  "Regional 18": [
    "Morada dos Pássaros",
    "Cid. Vera Cruz 1",
    "Goiania Park Sul",
    "Jardim Veneza",
  ],
  "Regional 19": [
    "Setor Cristina",
    "Jardim Marista",
    "Serra Branca",
    "Rosa Morena",
    "Vida Nova",
  ],
  "Regional 20": [
    "Jardim Scala",
    "Maisa 2",
    "Renata Parque",
    "Setor dos Bandeirantes",
  ],
  "Regional 21": [
    "Tiradentes",
    "Parque Haiala",
    "Independencia  Mansões",
    "Vila Delfiori",
  ],
};
