/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SorteioRouteImport } from './routes/sorteio'
import { Route as SortearRouteImport } from './routes/sortear'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GanhadoresRouteImport } from './routes/ganhadores'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteioRoute = SorteioRouteImport.update({
  id: '/sorteio',
  path: '/sorteio',
  getParentRoute: () => rootRouteImport,
} as any)
const SortearRoute = SortearRouteImport.update({
  id: '/sortear',
  path: '/sortear',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GanhadoresRoute = GanhadoresRouteImport.update({
  id: '/ganhadores',
  path: '/ganhadores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ganhadores': typeof GanhadoresRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sortear': typeof SortearRoute
  '/sorteio': typeof SorteioRoute
  '/super-admin': typeof SuperAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ganhadores': typeof GanhadoresRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sortear': typeof SortearRoute
  '/sorteio': typeof SorteioRoute
  '/super-admin': typeof SuperAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ganhadores': typeof GanhadoresRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sortear': typeof SortearRoute
  '/sorteio': typeof SorteioRoute
  '/super-admin': typeof SuperAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ganhadores'
    | '/sitemap.xml'
    | '/sortear'
    | '/sorteio'
    | '/super-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ganhadores'
    | '/sitemap.xml'
    | '/sortear'
    | '/sorteio'
    | '/super-admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ganhadores'
    | '/sitemap.xml'
    | '/sortear'
    | '/sorteio'
    | '/super-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  GanhadoresRoute: typeof GanhadoresRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SortearRoute: typeof SortearRoute
  SorteioRoute: typeof SorteioRoute
  SuperAdminRoute: typeof SuperAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteio': {
      id: '/sorteio'
      path: '/sorteio'
      fullPath: '/sorteio'
      preLoaderRoute: typeof SorteioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sortear': {
      id: '/sortear'
      path: '/sortear'
      fullPath: '/sortear'
      preLoaderRoute: typeof SortearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ganhadores': {
      id: '/ganhadores'
      path: '/ganhadores'
      fullPath: '/ganhadores'
      preLoaderRoute: typeof GanhadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  GanhadoresRoute: GanhadoresRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SortearRoute: SortearRoute,
  SorteioRoute: SorteioRoute,
  SuperAdminRoute: SuperAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
